name: painkiller-project
services:
  postgres:
    image: postgres:16-alpine
    container_name: painkiller-db
    ports:
      - "${POSTGRES_PORT_OUT}:5432"
      # - 5003:5432
    volumes:
      - painkiller-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - painkiller-net

  backend:
    build: ./backend
    container_name: painkiller-backend
    ports:
      - ${BackendPORT}:3003
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - painkiller-net
    env_file:
      - ./.env
    # command: >
    #   sh -c "
    #   npm run db:push &&
    #   npm run start
    #   "
  frontend:
    container_name: painkiller-frontend
    build: ./frontend
    ports:
      - ${NGINX_PORT}:7003
    networks:
      - painkiller-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}

volumes:
  painkiller-data:

networks:
  painkiller-net:
    driver: bridge
