name: painkiller # You can also change this to another name to avoid warning with existing group. 
services:
  backend:
    container_name: poinkiller-backend
    build: .
    ports:
      - ${PORT}:3000
    networks:
      - painkiller-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
  postgres:
    image: postgres:16-alpine
    container_name: painkiller-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - painkiller-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - painkiller-net
volumes:
  painkiller-data:
networks:
  painkiller-net: # Check by using `docker network ls` command
    external: true